version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: git submodule update --init
      - run: git submodule update --init --recursive --remote
      - restore_cache:
          key: lms-dependency-cache-{{ checksum "pom.xml" }}
      - run: mvn clean install
      - save_cache:
          key: lms-dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2
      - run:
          name: Analyze on SonarCloud
          command: mvn verify -Dskiptest=true sonar:sonar -Dsonar.projectKey=project-sunbird_sunbird-lms-mw -Dsonar.organization=project-sunbird -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.jacoco.xmlReportPaths=/home/circleci/project/actors/sunbird-utils/notification-sdk/target/site/jacoco/jacoco.xml,/home/circleci/project/actors/sunbird-utils/sunbird-platform-core/common-util/target/site/jacoco/jacoco.xml,/home/circleci/project/actors/sunbird-utils/sunbird-es-utils/target/site/jacoco/jacoco.xml,/home/circleci/project/actors/sunbird-utils/sunbird-notification/target/site/jacoco/jacoco.xml,/home/circleci/project/actors/sunbird-utils/sunbird-cassandra-utils/target/site/jacoco/jacoco.xml,/home/circleci/project/actors/location/target/site/jacoco/jacoco.xml,/home/circleci/project/actors/common/target/site/jacoco/jacoco.xml,/home/circleci/project/actors/systemsettings/target/site/jacoco/jacoco.xml,/home/circleci/project/actors/user/target/site/jacoco/jacoco.xml,/home/circleci/project/actors/badge/target/site/jacoco/jacoco.xml

workflows:
  version: 2.1
  workflow:
    jobs:
      - build
